services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - .config/mosquitto/config:/mosquitto/config
    restart: unless-stopped

  dashboard:
    build: ./services/dashboard
    container_name: dashboard
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./shared/mqtt.yaml:/app/mqtt.yaml:ro
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883
    depends_on:
      - broker
    restart: unless-stopped

  controller:
    build: ./services/controller
    container_name: controller
    ports:
      - "0.0.0.0:8081:8081"
    volumes:
      - ./shared/mqtt.yaml:/app/mqtt.yaml:ro
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883
    depends_on:
      - broker
    restart: unless-stopped

  logger:
    build: ./services/logger
    container_name: logger
    volumes:
      - ./shared/mqtt.yaml:/app/mqtt.yaml:ro
      - ./shared/logs.txt:/app/logs.txt
    environment:
      - TZ=Australia/Sydney

networks:
  network:
    driver: bridge